NameSpace: koden-clients
AppName: ozone-db

MariadbReplicas: 1
MariadbImageTag: latest
MariadbDiskSize: 50Gi
MariadbServerId: 3
MariadbDbName: ozoneshop_prod
MariadbDbUser: ozoneshop_prod
MariadbDbPort: 3306
