apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: ozone
type: Opaque
data:
  mysql-root-password: <value-base64>
  mysql-database: <value-base64>
  mysql-user: <value-base64>
  mysql-password: <value-base64>